import { AudioPost, Profile, CommunityPost } from './database.types'

export const mockProfiles: Profile[] = [
  {
    id: 'u1',
    username: 'asmr_sakura',
    display_name: '桜 ASMR',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sakura',
    bio: 'ASMRクリエイター。癒しの音をお届けします🌸',
    sns_links: { twitter: 'https://twitter.com', youtube: 'https://youtube.com' },
    is_poster: true,
    is_premium: true,
    custom_url: 'sakura',
    follower_count: 12400,
    following_count: 234,
    total_plays: 890000,
    level: 6,
    badges: ['early_adopter', 'hall_of_fame'],
    theme_template: 'sakura',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'u2',
    username: 'voice_drama_riku',
    display_name: 'リク・ドラマ',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=riku',
    bio: '音声ドラマを制作しています。物語の世界へようこそ🎭',
    sns_links: { twitter: 'https://twitter.com' },
    is_poster: true,
    is_premium: false,
    custom_url: 'riku',
    follower_count: 8700,
    following_count: 156,
    total_plays: 450000,
    level: 5,
    badges: ['top_poster'],
    theme_template: 'dark',
    created_at: '2024-02-20T00:00:00Z',
  },
  {
    id: 'u3',
    username: 'talk_mana',
    display_name: 'まな・トーク',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mana',
    bio: '日常トークと癒しボイス。毎日配信中！',
    sns_links: {},
    is_poster: true,
    is_premium: true,
    custom_url: 'mana',
    follower_count: 5200,
    following_count: 89,
    total_plays: 230000,
    level: 4,
    badges: ['premium_creator'],
    theme_template: 'default',
    created_at: '2024-03-10T00:00:00Z',
  },
  {
    id: 'u4',
    username: 'music_haru',
    display_name: 'はる Music',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=haru',
    bio: 'オリジナル音楽と歌声をシェアしています🎵',
    sns_links: { soundcloud: 'https://soundcloud.com' },
    is_poster: true,
    is_premium: false,
    custom_url: 'haru',
    follower_count: 3100,
    following_count: 421,
    total_plays: 120000,
    level: 3,
    badges: [],
    theme_template: 'default',
    created_at: '2024-04-05T00:00:00Z',
  },
  {
    id: 'u5',
    username: 'asmr_yuki',
    display_name: 'ゆき ASMR',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yuki',
    bio: '眠れない夜のASMR配信。ゆっくりしていってね🌙',
    sns_links: {},
    is_poster: true,
    is_premium: false,
    custom_url: null,
    follower_count: 1800,
    following_count: 67,
    total_plays: 78000,
    level: 3,
    badges: [],
    theme_template: 'default',
    created_at: '2024-05-01T00:00:00Z',
  },
]

export const mockAudioPosts: AudioPost[] = [
  {
    id: 'a1',
    poster_id: 'u1',
    title: '雨の日のASMR - 傘の音と囁き声',
    description: '雨の日に聴きたいASMR。傘を叩く雨音と優しい囁き声でリラックス。眠れない夜や作業中のBGMにどうぞ🌧️',
    tags: ['ASMR', '雨音', '囁き', 'リラックス', '睡眠'],
    category: 'ASMR',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3',
    thumbnail_url: 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=400&h=400&fit=crop',
    duration: 3240,
    file_size: 45000000,
    play_count: 156800,
    like_count: 12400,
    visibility: 'public',
    series_id: null,
    episode_number: null,
    language: 'ja',
    age_restricted: false,
    is_premium_only: false,
    is_hall_of_fame: true,
    scheduled_at: null,
    published_at: '2024-12-01T10:00:00Z',
    created_at: '2024-12-01T09:00:00Z',
    updated_at: '2024-12-01T09:00:00Z',
    deleted_at: null,
    poster: mockProfiles[0],
  },
  {
    id: 'a2',
    poster_id: 'u2',
    title: '夜の図書館 - 音声ドラマ第1話',
    description: '深夜の図書館で出会った不思議な少女。彼女が持つ古い本に秘められた謎とは...',
    tags: ['音声ドラマ', 'ミステリー', '図書館', 'オリジナル'],
    category: '音声ドラマ',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3',
    thumbnail_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=400&fit=crop',
    duration: 2580,
    file_size: 36000000,
    play_count: 89200,
    like_count: 7800,
    visibility: 'public',
    series_id: 's1',
    episode_number: 1,
    language: 'ja',
    age_restricted: false,
    is_premium_only: false,
    is_hall_of_fame: false,
    scheduled_at: null,
    published_at: '2024-12-05T12:00:00Z',
    created_at: '2024-12-05T11:00:00Z',
    updated_at: '2024-12-05T11:00:00Z',
    deleted_at: null,
    poster: mockProfiles[1],
  },
  {
    id: 'a3',
    poster_id: 'u3',
    title: '今日あったこと話す - まなの日常トーク #42',
    description: '今日は友達とカフェに行ったんだけど、面白いことがあって...',
    tags: ['トーク', '日常', '雑談', 'ほっこり'],
    category: 'トーク',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3',
    thumbnail_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop',
    duration: 1800,
    file_size: 25000000,
    play_count: 45600,
    like_count: 3200,
    visibility: 'public',
    series_id: null,
    episode_number: null,
    language: 'ja',
    age_restricted: false,
    is_premium_only: false,
    is_hall_of_fame: false,
    scheduled_at: null,
    published_at: '2024-12-08T18:00:00Z',
    created_at: '2024-12-08T17:00:00Z',
    updated_at: '2024-12-08T17:00:00Z',
    deleted_at: null,
    poster: mockProfiles[2],
  },
  {
    id: 'a4',
    poster_id: 'u4',
    title: 'Starlight Serenade - Original Acoustic',
    description: 'アコースティックギターで弾いたオリジナル曲。夜空を見上げながら聴いてほしい。',
    tags: ['音楽', 'ギター', 'オリジナル', 'アコースティック'],
    category: '音楽',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3',
    thumbnail_url: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=400&fit=crop',
    duration: 240,
    file_size: 8000000,
    play_count: 32100,
    like_count: 2900,
    visibility: 'public',
    series_id: null,
    episode_number: null,
    language: 'ja',
    age_restricted: false,
    is_premium_only: false,
    is_hall_of_fame: false,
    scheduled_at: null,
    published_at: '2024-12-10T14:00:00Z',
    created_at: '2024-12-10T13:00:00Z',
    updated_at: '2024-12-10T13:00:00Z',
    deleted_at: null,
    poster: mockProfiles[3],
  },
  {
    id: 'a5',
    poster_id: 'u5',
    title: '眠れない夜のお耳かき ASMR 1時間',
    description: 'ゆっくりとしたお耳かきの音で心地よく眠れますように。ヘッドフォン推奨🎧',
    tags: ['ASMR', '耳かき', '睡眠', '1時間'],
    category: 'ASMR',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3',
    thumbnail_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop',
    duration: 3600,
    file_size: 50000000,
    play_count: 78900,
    like_count: 6700,
    visibility: 'public',
    series_id: null,
    episode_number: null,
    language: 'ja',
    age_restricted: false,
    is_premium_only: true,
    is_hall_of_fame: false,
    scheduled_at: null,
    published_at: '2024-12-12T20:00:00Z',
    created_at: '2024-12-12T19:00:00Z',
    updated_at: '2024-12-12T19:00:00Z',
    deleted_at: null,
    poster: mockProfiles[4],
  },
  {
    id: 'a6',
    poster_id: 'u1',
    title: 'カフェのASMR - コーヒーを淹れる音',
    description: 'コーヒーを丁寧に淹れる音。豆を挽く音からドリップまで。',
    tags: ['ASMR', 'コーヒー', 'カフェ', '作業用'],
    category: 'ASMR',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3',
    thumbnail_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop',
    duration: 1800,
    file_size: 25000000,
    play_count: 62300,
    like_count: 5100,
    visibility: 'public',
    series_id: null,
    episode_number: null,
    language: 'ja',
    age_restricted: false,
    is_premium_only: false,
    is_hall_of_fame: false,
    scheduled_at: null,
    published_at: '2024-12-14T08:00:00Z',
    created_at: '2024-12-14T07:00:00Z',
    updated_at: '2024-12-14T07:00:00Z',
    deleted_at: null,
    poster: mockProfiles[0],
  },
  {
    id: 'a7',
    poster_id: 'u2',
    title: '夜の図書館 - 音声ドラマ第2話「古い手紙」',
    description: '前回見つかった古い本の中に挟まれていた手紙。差出人は100年前に亡くなった少女だった...',
    tags: ['音声ドラマ', 'ミステリー', '図書館', 'シリーズ'],
    category: '音声ドラマ',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3',
    thumbnail_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=400&fit=crop',
    duration: 2820,
    file_size: 39000000,
    play_count: 71500,
    like_count: 6300,
    visibility: 'public',
    series_id: 's1',
    episode_number: 2,
    language: 'ja',
    age_restricted: false,
    is_premium_only: false,
    is_hall_of_fame: false,
    scheduled_at: null,
    published_at: '2024-12-15T12:00:00Z',
    created_at: '2024-12-15T11:00:00Z',
    updated_at: '2024-12-15T11:00:00Z',
    deleted_at: null,
    poster: mockProfiles[1],
  },
  {
    id: 'a8',
    poster_id: 'u3',
    title: 'プレミアム限定！深夜の秘密トーク',
    description: 'プレミアム会員限定の深夜トーク。普段は話せない本音話します。',
    tags: ['トーク', '限定', 'プレミアム'],
    category: 'トーク',
    audio_url: 'https://www.soundjay.com/misc/sounds/bell-ringing-01.mp3',
    thumbnail_url: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&h=400&fit=crop',
    duration: 2400,
    file_size: 33000000,
    play_count: 28900,
    like_count: 4100,
    visibility: 'public',
    series_id: null,
    episode_number: null,
    language: 'ja',
    age_restricted: false,
    is_premium_only: true,
    is_hall_of_fame: false,
    scheduled_at: null,
    published_at: '2024-12-16T23:00:00Z',
    created_at: '2024-12-16T22:00:00Z',
    updated_at: '2024-12-16T22:00:00Z',
    deleted_at: null,
    poster: mockProfiles[2],
  },
]

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 'cp1',
    user_id: 'u1',
    category: 'general',
    content: '新しいASMRをアップしました！今回は雨音と囁き声のコラボレーションです。ぜひ聴いてみてください🌧️',
    like_count: 89,
    created_at: '2024-12-15T10:00:00Z',
    user: mockProfiles[0],
  },
  {
    id: 'cp2',
    user_id: 'u2',
    category: 'announcements',
    content: '「夜の図書館」シリーズ第3話の制作が始まりました！今回は謎が一気に明かされる展開になります。お楽しみに🎭',
    like_count: 134,
    created_at: '2024-12-15T14:00:00Z',
    user: mockProfiles[1],
  },
  {
    id: 'cp3',
    user_id: 'u3',
    category: 'feedback',
    content: 'みなさんはどんなジャンルのトークが聴きたいですか？日常トーク、恋愛相談、怖い話など、リクエストお待ちしています！',
    like_count: 67,
    created_at: '2024-12-14T18:00:00Z',
    user: mockProfiles[2],
  },
  {
    id: 'cp4',
    user_id: 'u4',
    category: 'introductions',
    content: 'はじめまして！音楽クリエイターのはるです。アコースティックギターが専門で、これからオリジナル曲をたくさんアップしていきます🎸',
    like_count: 45,
    created_at: '2024-12-14T09:00:00Z',
    user: mockProfiles[3],
  },
]

export const TRENDING_AUDIOS = mockAudioPosts.slice(0, 6)
export const RECENT_AUDIOS = [...mockAudioPosts].reverse().slice(0, 8)
export const FEATURED_AUDIO = mockAudioPosts[0]
